import type { WarehouseStore } from "../store/duckdb.js";
import {
  allChecksPassed,
  buildCheckQuery,
  DqRunResultSchema,
  evaluateCheck,
  type DqCheckResult,
  type DqRunResult,
  type DqSpec,
} from "../core/dq.js";

/**
 * The `run_dq_check` tool (PRD FR7, ARCHITECTURE §5) — executes the reviewed data-quality checks
 * against the loaded source table and reports pass/fail per check plus the aggregate the pipeline
 * gates on. **Any failure blocks publish** (`DqRunResult.passed === false`); the pipeline runner
 * (T4.4/T5.1) turns a failing run into a failed run so the later Publish stage never executes —
 * the deterministic-runner realization of ARCHITECTURE §5's `tool.execute.before` guard.
 *
 * Unlike the write/execute tools it is read-only (permission `allow`): it only runs `SELECT`
 * counts, mutating nothing. An I/O module (DuckDB queries), so it lives under `server/tools`; the
 * check-to-SQL translation, the pass/fail interpretation, and the block-publish rule are the pure
 * {@link file://../core/dq.ts}.
 */

/** Inputs the `run_dq_check` tool needs to execute one reviewed DQ spec. */
export interface RunDqCheckInput {
  /** The reviewed spec (target table + ≥3 checks) generated by the DQ stage and approved. */
  spec: DqSpec;
}

/**
 * Execute every check in the spec against its target table, returning one {@link DqCheckResult}
 * per check plus the aggregate `passed` flag. Each check runs an independent metric query
 * ({@link buildCheckQuery}); a query that throws (e.g. the column does not exist) is recorded as a
 * **failed** check with the error detail rather than aborting the whole run — so one malformed
 * check cannot mask the others, and a missing column honestly fails its check. The aggregate is
 * `false` if any single check failed, which is what blocks publish (FR7).
 */
export async function runDqCheck(
  store: WarehouseStore,
  input: RunDqCheckInput,
): Promise<DqRunResult> {
  const { spec } = input;
  const results: DqCheckResult[] = [];

  for (const check of spec.checks) {
    let result: DqCheckResult;
    try {
      const query = buildCheckQuery(check, spec.targetTable);
      const rows = await store.all(query.sql, query.params);
      const metric = Number(rows[0]?.metric ?? 0);
      const { passed, detail } = evaluateCheck(check, metric);
      result = { name: check.name, type: check.type, column: check.column, passed, detail };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      result = {
        name: check.name,
        type: check.type,
        column: check.column,
        passed: false,
        detail: `check errored: ${message}`,
      };
    }
    results.push(result);
  }

  return DqRunResultSchema.parse({
    targetTable: spec.targetTable,
    results,
    passed: allChecksPassed(results),
  });
}
