import type { WarehouseStore } from "../store/duckdb.js";
import {
  MARTS_SCHEMA,
  RunTransformResultSchema,
  type RunTransformResult,
} from "../core/transform.js";
import { safeTableName } from "../core/warehouse.js";

/**
 * The `run_transform` tool (PRD FR6, ARCHITECTURE §5) — "the riskiest tool." It executes the
 * transformation SQL a human already reviewed and approved, materializing the final business
 * table in the DuckDB `marts` schema (the "Transform" pipeline stage). Because it runs SQL that
 * mutates the warehouse, it is permission **`ask`** (it is on {@link file://../opencode/config.ts}'s
 * `ASK_TOOLS`); the run pauses for explicit approval before it executes (FR8). An I/O module
 * (DuckDB DDL), so it lives under `server/tools`; the pure parts — the `marts` schema constant,
 * the result shape — are in {@link file://../core/transform.ts}, and the identifier sanitizer is
 * shared with the load tool ({@link file://../core/warehouse.ts}).
 */

/** Inputs the `run_transform` tool needs to execute one reviewed transform. */
export interface RunTransformInput {
  /**
   * The reviewed transformation SQL to execute — a `CREATE OR REPLACE TABLE marts.<target> AS
   * SELECT ... FROM raw.source ...` statement (as generated by the transform stage and approved
   * by a human at the FR8 gate). Executed verbatim; the human approved this exact text.
   */
  sql: string;
  /**
   * Unqualified name of the `marts` table the SQL creates (the `Transform.targetTable`). Used to
   * read the result back for the row count; sanitized to a bare identifier first.
   */
  targetTable: string;
}

/** Escape a string for safe interpolation as a double-quoted SQL identifier. */
function quoteIdent(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

/**
 * Execute the reviewed transform SQL, then read `marts.<targetTable>` back to report the row
 * count (FR6). The SQL runs verbatim — a human reviewed and approved this exact statement at the
 * FR8 gate — while the `targetTable` used to build the read-back count is sanitized to a bare
 * identifier and double-quoted so a crafted name cannot inject. Reading the result back from
 * `marts` also enforces that the reviewed SQL actually produced the marts table it claimed: if
 * the statement wrote nowhere (or to another schema), the count throws.
 *
 * Throws when `sql` is empty/whitespace, when the SQL fails to execute (the DuckDB error
 * propagates), or when it did not create `marts.<targetTable>` — the caller (T4.4 runner) maps
 * those to a run-step failure.
 */
export async function runTransform(
  store: WarehouseStore,
  input: RunTransformInput,
): Promise<RunTransformResult> {
  const sql = input.sql.trim();
  if (sql.length === 0) {
    throw new Error("run_transform: refusing to execute empty transform SQL");
  }

  const table = safeTableName(input.targetTable);
  const qualifiedTable = `${MARTS_SCHEMA}.${table}`;
  const target = `${MARTS_SCHEMA}.${quoteIdent(table)}`;

  // Execute the reviewed statement verbatim — this is the exact SQL a human approved.
  await store.run(sql);

  // Count rows by reading the created marts table back — proves the transform persisted and
  // that the SQL actually materialized marts.<targetTable> (a plain count(*), no partition-col
  // aggregate, to avoid the DuckDB statistics bug the land tool documents).
  const counted = await store.all(
    `SELECT count(*)::BIGINT AS row_count FROM ${target}`,
  );
  const rowCount = Number(counted[0]?.row_count ?? 0);

  return RunTransformResultSchema.parse({
    schema: MARTS_SCHEMA,
    table,
    qualifiedTable,
    rowCount,
  });
}
